### ISSUE TITLE
Test host for multiple contracts

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-rust-smart-contracts#107]
Currently the `TestHost` have functionality to mock an entrypoint.

It would be nice to extend this with functionality to setup another contract with state for an entrypoint, for applications which have multiple smart contracts, such as an NFT contract and a listing contract.

**Comment by DOBEN** [comment]
That would be a very nice feature and help a lot in building/testing large-scale protocols. If we can have several smart contracts with some state in the test cases so that we can test the outcome of a function invoke that updates the state of several smart contracts that would be brilliant. I strongly support this feature.

**Comment by abizjak** [comment]
Since we are migrating away from the test host to use the smart contract testing library, I am closing this.
