### ISSUE TITLE
Generating template - duplicated url example in  the user interface

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-rust-smart-contracts#173]
**Bug Description**
While generating cis2-nft template, duplicated url example appears in the ui.

**Steps to Reproduce**
Try to generate cis2-nft template `cargo concordium init`
Insert valid project name and description

**Expected Result**
` Token metadata base URL of the token? [default: https://some.example/token/]:`

**Actual Result**
` Token metadata base URL of the token? [default: https://some.example/token/] [https://some.example/token/]:`

**Versions**
- Software Version

**Comment by DOBEN** [comment]
The duplicated string is part of cargo-generate behavior (most likely the first mention means that the default value is as `https...` and the second mention means that if the user presses enter that value will be already filled in. It is not part of our templates.

[default value in template](https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/templates/cis2-nft/cargo-generate.toml#L6)

I could remove the default option as follows :arrow_down:, then the user is forced to input a string every time (instead of pressing just enter but we have removed the duplicated content). I would probably prefer still the old flow since it is more convenient for the user to press enter.
`tokenMetadataBaseURL= { type="bool", prompt="Token metadata base URL of the token? (Example: https://some.example/token/)"}`

**Comment by abizjak** [comment]
As per the comment above, we decided that the current behaviour is better for the user.
